### ISSUE TITLE
Allow punctuation

### ISSUE THREAD

**Issue by Aldredcz** [chuyik/brackets-snippets#10] opened 2015-02-27 15:37 UTC
I really like this plugin, but I don't understand, why some punctuation is forbidden. I'd like to use ';trigger', but can't. Is it really necessary to restrict it?

**Comment by chuyik** [comment] 2015-02-28 01:19
Wonder if you are using the latest version, ';trigger' should be supported.

**Comment by Aldredcz** [comment] 2015-02-28 12:49
Brackets version 1.1 build 1.1.0-15558 (release ea908cae5) 
Brackets Snippets (by edc) version 1.5.0

Even it says "White spaces and punctuations are permitted", it makes the field invalid and I'm not able to Save.

![image](https://cloud.githubusercontent.com/assets/6008904/6426222/7fbc6900-bf50-11e4-9e2b-f37aedfb31f1.png)

**Comment by chuyik** [comment] 2015-02-28 15:07
Oh sorry I misunderstood your meaning, I thought that you mean the hint list couldn't show up if it's after ';'.

And I think I also forgot to add `NOT` to the message you mentioned :joy: Really sorry for that...
The punctuations are not allowed to be a part of trigger by design, because I need to use the punctuations as separators to get the last word users are typing, and compare it with the triggers of the snippets.

If support the punctuations, it may become complicated, and I also wonder the usefulness of this.
So reopen this for more advice, and thanks for your comments and love!

The extension has not been updated for long since the festival in China, but new version of this would be released soon, hope you could try it and leave me more feedback!

Regards.

**Comment by Aldredcz** [comment] 2015-03-02 17:05
Well, I'm used to ';' as starting character of snippets from other environments, but i think, i can live without it. Actually, what bothered me more and didn't know about it is issue https://github.com/chuyik/brackets-snippets/issues/9

You can close this one.

**Comment by chuyik** [comment] 2015-03-03 02:27
@Aldredcz the #9 is fixed in new version, please check it out!
And I will take this in consideration, so just leave it open and hear more voices.

**Comment by ldminoc** [comment] 2015-03-18 03:32
@chuyik, punctuation such as {{ is used by templating languages such as mustache, handlebars and htmlbars. {{ is perfect for the start of a trigger for the various constructs of those languages.

**Comment by s4wny** [comment] 2015-03-20 18:32
I also would like to be able to have `/` as a triggers. (In sublime text i have a snippet for /* that becomes a PHP DOC).

I think the only characters that shouldn't be allowed is ` ` (white space), '\t', `\r`, '\n', '\r\n' and `.`. That will support most user cases:

```
/*[tab]  (newline is the separator)

function foo()
{
    new Class().meth[tab] (. is the separator expand to some method)
    
    for[tab] (space/tab is the separator)

    echo "foobar" + foo[tab] (whitespace is separator).
}
```

**Closed** 2017-12-05 13:03 UTC
Labels: enhancement
